{
 "title": "GitLab Omnibus - PostgreSQL",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"postgresql\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(pg_up{job=\"postgresql\",instance=~\"$instance\"}[$__interval]) or avg_over_time(up{job=\"postgresql\",instance=~\"$instance\"}[$__interval]) "
    }
   ]
  },
  {
   "title": "Postmaster Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(time() - pg_postmaster_start_time_seconds{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (\n  avg_over_time(pg_locks_count{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(pg_slow_queries{instance=~\"$instance\"}[$__interval])\n)",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(\n  rate(pg_slow_queries{instance=~\"$instance\"}[$__interval] offset 1w)\n)",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(pg_stat_activity_count{instance=~\"$instance\",state=\"active\"}[$__interval])) /\nsum(pg_settings_max_connections{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(pg_stat_activity_count{instance=~\"$instance\"}[$__interval])) /\nsum(pg_settings_max_connections{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(pg_stat_database_xact_commit{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "Commit"
    },
    {
     "expr": "sum(\n  rate(pg_stat_database_xact_rollback{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "Block IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(pg_stat_database_blks_hit{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "sum(\n  rate(pg_stat_database_blks_read{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "Tuple Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(pg_stat_database_tup_fetched{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(\n  rate(pg_stat_database_tup_deleted{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "Deleted"
    },
    {
     "expr": "sum(\n  rate(pg_stat_database_tup_inserted{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(\n  rate(pg_stat_database_tup_updated{instance=~\"$instance\",datname=\"gitlabhq_production\"}[$__interval])\n)",
     "legendFormat": "Updated"
    }
   ]
  }
 ]
}