apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus
  namespace: nexus
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath
